---
version: "3.7"
services:

  # ---------------------------------------------------------------------
  # | Nginx-Service                                                     |
  # ---------------------------------------------------------------------
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80" # Exposes port 80 for incomming web requests
    volumes:
      # Mounts the nginx configuration file
      # the section after collon is the path inside the container, do not chenge it if you don't know what you are doing
      - ../../frontend/nginx/dist:/usr/share/nginx/html
