---
name: Develop Docker
on:
  push:
    branches-ignore:
      - release
      - main
      - develop
  workflow_call:

jobs:
  test-docker:
    name: Test Docker
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "🔍  Verify Changed Nginx files ./docker or *.Dockerfile"
        uses: tj-actions/changed-files@v23.1
        id: changed-nginx-docker
        with:
          files: |
              docker/*.nginx.yml

      - name: "🐳  Start Nginx Docker Containers"
        if: steps.changed-nginx-docker.outputs.any_changed == 'true'
        run: bash scripts/docker-nginx-start.bash
  
      - name: "🧪  List running containers"
        if: steps.changed-nginx-docker.outputs.any_changed == 'true'
        run: docker ps -a
  
      - name: "🧪 Test Nginx container"
        if: steps.changed-nginx-docker.outputs.any_changed == 'true'
        run: bash scripts/docker-nginx-test.bash
